// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/inputs/interfaces.go

// Package mock_inputs is a generated GoMock package.
package mock_inputs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	clogger "github.com/sinkingpoint/clogger/internal/clogger"
)

// MockInputter is a mock of Inputter interface.
type MockInputter struct {
	ctrl     *gomock.Controller
	recorder *MockInputterMockRecorder
}

// MockInputterMockRecorder is the mock recorder for MockInputter.
type MockInputterMockRecorder struct {
	mock *MockInputter
}

// NewMockInputter creates a new mock instance.
func NewMockInputter(ctrl *gomock.Controller) *MockInputter {
	mock := &MockInputter{ctrl: ctrl}
	mock.recorder = &MockInputterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputter) EXPECT() *MockInputterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInputter) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockInputterMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInputter)(nil).Close), ctx)
}

// GetBatch mocks base method.
func (m *MockInputter) GetBatch(ctx context.Context) (*clogger.MessageBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatch", ctx)
	ret0, _ := ret[0].(*clogger.MessageBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatch indicates an expected call of GetBatch.
func (mr *MockInputterMockRecorder) GetBatch(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatch", reflect.TypeOf((*MockInputter)(nil).GetBatch), ctx)
}

// Init mocks base method.
func (m *MockInputter) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockInputterMockRecorder) Init(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockInputter)(nil).Init), ctx)
}
